version: '3.8'
services:
  api:
    build: .
    container_name: azure_openai_api
    ports:
      - "3555:3555"
    environment:
      AZURE_OPENAI_API_KEY: "api_key" 
      AZURE_OPENAI_ENDPOINT: "https://oai-empresa-curriculums.openai.azure.com"
      AZURE_OPENAI_DEPLOYMENT_NAME: "nombre_del_despliegue"
      AZURE_OPENAI_API_VERSION: "2024-02-01"
      AZURE_MODEL_NAME: "GPT-4o mini"
    restart: unless-stopped
    networks:
      - network_1

networks:
 network_1:
    external: true